version: "2"

run:
  tests: true
  build-tags:
    - bench
    - "!bench"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx

  exclusions:
    rules:
      - path: '_test\.go$'
        linters:
          - depguard
      - path: '.*\.go$'
        text: 'weak cryptographic primitive'
        linters:
          - gosec